# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ExpenseTracker CICD

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: idockerwas/expense-tracker

    steps:
    - name: checking out repository code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file back-services/ds-service/pom.xml
    
    - name: Debug:Find the generated JAR files
      run: find back-services/ds-service/ -name "*.jar"
    - name: Login to Docker
      if: github.event_name=='push'
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: ✅ Debug:List contents of Docker build context
      if: github.event_name=='push'
      run: ls -R back-services/ds-service/
    - name: Build Docker image
      if: github.event_name=='push'
      run: docker build -f back-services/ds-service/Dockerfile back-services/ds-service -t $IMAGE_NAME:${{ github.sha }}
    - name: deploye
      if: github.event_name=='push'
      run: docker push $IMAGE_NAME:${{ github.sha }}
      

   
